[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 5173

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"
