name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      http_proxy: ''
      https_proxy: ''
      HTTP_PROXY: ''
      HTTPS_PROXY: ''
      npm_config_http_proxy: ''
      npm_config_https_proxy: ''
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: node ./check-version-bump.mjs
      - run: npm install
      - run: npm test
      - run: npm run build
