name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - name: Lint
        run: node ./lint-interactions.mjs
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
